# Generated by Django 3.1.3 on 2020-11-25 05:03

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('elevation', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
